#############################################################################
# Makefile for building: libzsengine.a
# Generated by qmake (3.1) (Qt 5.12.4)
# Project:  ZSpireEngine.pro
# Template: lib
# Command: /usr/lib/qt5/bin/qmake -o Makefile ZSpireEngine.pro
#############################################################################

MAKEFILE      = Makefile

EQ            = =

####### Compiler, tools and options

CC            = gcc
CXX           = g++
DEFINES       = -DQT_DEPRECATED_WARNINGS -DQT_NO_DEBUG
CFLAGS        = -pipe -O2 -fPIC -Wall -W -D_REENTRANT $(DEFINES)
CXXFLAGS      = -pipe -O2 -fPIC -Wall -W -D_REENTRANT $(DEFINES)
INCPATH       = -I. -I/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++
QMAKE         = /usr/lib/qt5/bin/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
QINSTALL      = /usr/lib/qt5/bin/qmake -install qinstall
QINSTALL_PROGRAM = /usr/lib/qt5/bin/qmake -install qinstall -exe
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = zsengine1.0.0
DISTDIR = /home/andrew/ZSPIRE/zspirengine/.tmp/zsengine1.0.0
AR            = ar cqs
RANLIB        = 
SED           = sed
STRIP         = strip

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = src/engine.cpp \
		src/vulkan/zsvulkan.cpp \
		src/render/zs-pipeline.cpp \
		src/render/zs-shader.cpp \
		src/render/zs-math.cpp \
		src/engine/resources.cpp \
		src/world/World.cpp \
		src/world/go_properties.cpp \
		src/world/GoProperty/tile_properties.cpp \
		src/world/GoProperty/go_filestream.cpp \
		src/world/GameObject.cpp \
		src/world/zs-camera.cpp \
		src/render/zs-mesh.cpp \
		src/engine/EngineManager.cpp \
		src/render/zs-texture.cpp \
		src/Scripting/LuaScript.cpp \
		src/engine/loader.cpp \
		src/misc/oal_manager.cpp \
		src/Scripting/zsensdk.cpp \
		src/misc/randomg.cpp \
		src/Scripting/zsensdk_input.cpp \
		src/ogl/ogl_mesh.cpp \
		src/vulkan/vk_mesh.cpp \
		src/ogl/ogl_uniform_buf.cpp \
		src/render/zs-uniform-buffer.cpp \
		src/vulkan/vk_uniform_buf.cpp \
		src/vulkan/zsvk_mem.cpp \
		src/ogl/ogl_shader.cpp \
		src/vulkan/vk_shader.cpp 
OBJECTS       = engine.o \
		zsvulkan.o \
		zs-pipeline.o \
		zs-shader.o \
		zs-math.o \
		resources.o \
		World.o \
		go_properties.o \
		tile_properties.o \
		go_filestream.o \
		GameObject.o \
		zs-camera.o \
		zs-mesh.o \
		EngineManager.o \
		zs-texture.o \
		LuaScript.o \
		loader.o \
		oal_manager.o \
		zsensdk.o \
		randomg.o \
		zsensdk_input.o \
		ogl_mesh.o \
		vk_mesh.o \
		ogl_uniform_buf.o \
		zs-uniform-buffer.o \
		vk_uniform_buf.o \
		zsvk_mem.o \
		ogl_shader.o \
		vk_shader.o
DIST          = /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		ZSpireEngine.pro headers/engine.h \
		headers/vulkan/zsvulkan.h \
		headers/render/zs-pipeline.h \
		headers/render/zs-shader.h \
		headers/render/zs-math.h \
		headers/engine/resources.h \
		headers/world/World.h \
		headers/world/go_properties.h \
		headers/game.h \
		headers/world/tile_properties.h \
		headers/engine/engine_window.h \
		headers/world/zs-camera.h \
		headers/render/zs-mesh.h \
		headers/engine/EngineManager.h \
		headers/render/zs-texture.h \
		headers/Scripting/LuaScript.h \
		headers/engine/loader.h \
		headers/engine_types.h \
		headers/misc/oal_manager.h \
		headers/Scripting/zsensdk.h \
		headers/misc/randomg.h \
		headers/ogl/ogl.h \
		headers/vulkan/vk_data.h \
		headers/render/zs-uniform-buffer.h \
		headers/vulkan/zsvk_mem.h src/engine.cpp \
		src/vulkan/zsvulkan.cpp \
		src/render/zs-pipeline.cpp \
		src/render/zs-shader.cpp \
		src/render/zs-math.cpp \
		src/engine/resources.cpp \
		src/world/World.cpp \
		src/world/go_properties.cpp \
		src/world/GoProperty/tile_properties.cpp \
		src/world/GoProperty/go_filestream.cpp \
		src/world/GameObject.cpp \
		src/world/zs-camera.cpp \
		src/render/zs-mesh.cpp \
		src/engine/EngineManager.cpp \
		src/render/zs-texture.cpp \
		src/Scripting/LuaScript.cpp \
		src/engine/loader.cpp \
		src/misc/oal_manager.cpp \
		src/Scripting/zsensdk.cpp \
		src/misc/randomg.cpp \
		src/Scripting/zsensdk_input.cpp \
		src/ogl/ogl_mesh.cpp \
		src/vulkan/vk_mesh.cpp \
		src/ogl/ogl_uniform_buf.cpp \
		src/render/zs-uniform-buffer.cpp \
		src/vulkan/vk_uniform_buf.cpp \
		src/vulkan/zsvk_mem.cpp \
		src/ogl/ogl_shader.cpp \
		src/vulkan/vk_shader.cpp
QMAKE_TARGET  = zsengine
DESTDIR       = 
TARGET        = libzsengine.a


first: all
####### Build rules

staticlib: $(TARGET)

libzsengine.a:  $(OBJECTS) $(OBJCOMP) 
	-$(DEL_FILE) $(TARGET)
	$(AR) $(DESTDIR)$(TARGET) $(OBJECTS)


Makefile: ZSpireEngine.pro /usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf /usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf \
		/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf \
		ZSpireEngine.pro
	$(QMAKE) -o Makefile ZSpireEngine.pro
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/linux.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/sanitize.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/gcc-base-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-base.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/common/g++-unix.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/qconfig.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_accessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_core_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_edid_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfs_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_glx_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_kms_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_linuxaccessibility_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_network_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_vulkan_support_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xcb_qpa_lib_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_functions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/linux-g++/qmake.conf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exclusive_builds.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/toolchain.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_pre.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/resolve_config.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/default_post.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/warn_on.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qt.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/unix/thread.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/qmake_use.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/file_copies.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/testcase_targets.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/exceptions.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/yacc.prf:
/usr/lib/x86_64-linux-gnu/qt5/mkspecs/features/lex.prf:
ZSpireEngine.pro:
qmake: FORCE
	@$(QMAKE) -o Makefile ZSpireEngine.pro

qmake_all: FORCE


all: Makefile libzsengine.a

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

check: first

benchmark: first

compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: 

####### Compile

engine.o: src/engine.cpp headers/engine.h \
		headers/vulkan/zsvulkan.h \
		headers/engine/engine_window.h \
		headers/engine/EngineManager.h \
		headers/engine_types.h \
		headers/engine/loader.h \
		headers/game.h \
		headers/world/World.h \
		headers/engine/resources.h \
		headers/render/zs-texture.h \
		headers/render/zs-mesh.h \
		headers/render/zs-math.h \
		headers/misc/oal_manager.h \
		headers/ogl/ogl.h \
		headers/render/zs-uniform-buffer.h \
		headers/render/zs-shader.h \
		headers/world/zs-camera.h \
		headers/vulkan/vk_data.h \
		headers/render/zs-pipeline.h \
		headers/Scripting/zsensdk.h \
		headers/Scripting/LuaScript.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o engine.o src/engine.cpp

zsvulkan.o: src/vulkan/zsvulkan.cpp headers/vulkan/zsvulkan.h \
		headers/engine/engine_window.h \
		headers/render/zs-shader.h \
		headers/render/zs-math.h \
		headers/engine.h \
		headers/engine/EngineManager.h \
		headers/engine_types.h \
		headers/world/zs-camera.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o zsvulkan.o src/vulkan/zsvulkan.cpp

zs-pipeline.o: src/render/zs-pipeline.cpp headers/render/zs-pipeline.h \
		headers/render/zs-shader.h \
		headers/render/zs-math.h \
		headers/engine.h \
		headers/vulkan/zsvulkan.h \
		headers/engine/engine_window.h \
		headers/engine/EngineManager.h \
		headers/engine_types.h \
		headers/world/zs-camera.h \
		headers/render/zs-mesh.h \
		headers/render/zs-uniform-buffer.h \
		headers/ogl/ogl.h \
		headers/vulkan/vk_data.h \
		headers/game.h \
		headers/world/World.h \
		headers/engine/resources.h \
		headers/render/zs-texture.h \
		headers/misc/oal_manager.h \
		headers/engine/loader.h \
		headers/world/go_properties.h \
		headers/Scripting/LuaScript.h \
		headers/Scripting/zsensdk.h \
		headers/world/tile_properties.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o zs-pipeline.o src/render/zs-pipeline.cpp

zs-shader.o: src/render/zs-shader.cpp headers/render/zs-shader.h \
		headers/render/zs-math.h \
		headers/engine.h \
		headers/vulkan/zsvulkan.h \
		headers/engine/engine_window.h \
		headers/engine/EngineManager.h \
		headers/engine_types.h \
		headers/world/zs-camera.h \
		headers/world/go_properties.h \
		headers/world/World.h \
		headers/engine/resources.h \
		headers/render/zs-texture.h \
		headers/render/zs-mesh.h \
		headers/misc/oal_manager.h \
		headers/engine/loader.h \
		headers/ogl/ogl.h \
		headers/render/zs-uniform-buffer.h \
		headers/vulkan/vk_data.h \
		headers/render/zs-pipeline.h \
		headers/Scripting/LuaScript.h \
		headers/Scripting/zsensdk.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o zs-shader.o src/render/zs-shader.cpp

zs-math.o: src/render/zs-math.cpp headers/render/zs-math.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o zs-math.o src/render/zs-math.cpp

resources.o: src/engine/resources.cpp headers/engine/resources.h \
		headers/render/zs-texture.h \
		headers/render/zs-mesh.h \
		headers/render/zs-math.h \
		headers/misc/oal_manager.h \
		headers/engine/loader.h \
		headers/engine/EngineManager.h \
		headers/engine_types.h \
		headers/ogl/ogl.h \
		headers/render/zs-uniform-buffer.h \
		headers/render/zs-shader.h \
		headers/engine.h \
		headers/vulkan/zsvulkan.h \
		headers/engine/engine_window.h \
		headers/world/zs-camera.h \
		headers/vulkan/vk_data.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o resources.o src/engine/resources.cpp

World.o: src/world/World.cpp headers/world/World.h \
		headers/engine/resources.h \
		headers/render/zs-texture.h \
		headers/render/zs-mesh.h \
		headers/render/zs-math.h \
		headers/misc/oal_manager.h \
		headers/engine/loader.h \
		headers/engine/EngineManager.h \
		headers/engine_types.h \
		headers/ogl/ogl.h \
		headers/render/zs-uniform-buffer.h \
		headers/render/zs-shader.h \
		headers/engine.h \
		headers/vulkan/zsvulkan.h \
		headers/engine/engine_window.h \
		headers/world/zs-camera.h \
		headers/vulkan/vk_data.h \
		headers/render/zs-pipeline.h \
		headers/misc/randomg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o World.o src/world/World.cpp

go_properties.o: src/world/go_properties.cpp headers/world/go_properties.h \
		headers/world/World.h \
		headers/engine/resources.h \
		headers/render/zs-texture.h \
		headers/render/zs-mesh.h \
		headers/render/zs-math.h \
		headers/misc/oal_manager.h \
		headers/engine/loader.h \
		headers/engine/EngineManager.h \
		headers/engine_types.h \
		headers/ogl/ogl.h \
		headers/render/zs-uniform-buffer.h \
		headers/render/zs-shader.h \
		headers/engine.h \
		headers/vulkan/zsvulkan.h \
		headers/engine/engine_window.h \
		headers/world/zs-camera.h \
		headers/vulkan/vk_data.h \
		headers/render/zs-pipeline.h \
		headers/Scripting/LuaScript.h \
		headers/Scripting/zsensdk.h \
		headers/world/tile_properties.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o go_properties.o src/world/go_properties.cpp

tile_properties.o: src/world/GoProperty/tile_properties.cpp headers/world/tile_properties.h \
		headers/world/go_properties.h \
		headers/world/World.h \
		headers/engine/resources.h \
		headers/render/zs-texture.h \
		headers/render/zs-mesh.h \
		headers/render/zs-math.h \
		headers/misc/oal_manager.h \
		headers/engine/loader.h \
		headers/engine/EngineManager.h \
		headers/engine_types.h \
		headers/ogl/ogl.h \
		headers/render/zs-uniform-buffer.h \
		headers/render/zs-shader.h \
		headers/engine.h \
		headers/vulkan/zsvulkan.h \
		headers/engine/engine_window.h \
		headers/world/zs-camera.h \
		headers/vulkan/vk_data.h \
		headers/render/zs-pipeline.h \
		headers/Scripting/LuaScript.h \
		headers/Scripting/zsensdk.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o tile_properties.o src/world/GoProperty/tile_properties.cpp

go_filestream.o: src/world/GoProperty/go_filestream.cpp headers/world/go_properties.h \
		headers/world/World.h \
		headers/engine/resources.h \
		headers/render/zs-texture.h \
		headers/render/zs-mesh.h \
		headers/render/zs-math.h \
		headers/misc/oal_manager.h \
		headers/engine/loader.h \
		headers/engine/EngineManager.h \
		headers/engine_types.h \
		headers/ogl/ogl.h \
		headers/render/zs-uniform-buffer.h \
		headers/render/zs-shader.h \
		headers/engine.h \
		headers/vulkan/zsvulkan.h \
		headers/engine/engine_window.h \
		headers/world/zs-camera.h \
		headers/vulkan/vk_data.h \
		headers/render/zs-pipeline.h \
		headers/Scripting/LuaScript.h \
		headers/Scripting/zsensdk.h \
		headers/world/tile_properties.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o go_filestream.o src/world/GoProperty/go_filestream.cpp

GameObject.o: src/world/GameObject.cpp headers/world/World.h \
		headers/engine/resources.h \
		headers/render/zs-texture.h \
		headers/render/zs-mesh.h \
		headers/render/zs-math.h \
		headers/misc/oal_manager.h \
		headers/engine/loader.h \
		headers/engine/EngineManager.h \
		headers/engine_types.h \
		headers/ogl/ogl.h \
		headers/render/zs-uniform-buffer.h \
		headers/render/zs-shader.h \
		headers/engine.h \
		headers/vulkan/zsvulkan.h \
		headers/engine/engine_window.h \
		headers/world/zs-camera.h \
		headers/vulkan/vk_data.h \
		headers/render/zs-pipeline.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o GameObject.o src/world/GameObject.cpp

zs-camera.o: src/world/zs-camera.cpp headers/world/zs-camera.h \
		headers/render/zs-math.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o zs-camera.o src/world/zs-camera.cpp

zs-mesh.o: src/render/zs-mesh.cpp headers/render/zs-mesh.h \
		headers/render/zs-math.h \
		headers/game.h \
		headers/world/World.h \
		headers/engine/resources.h \
		headers/render/zs-texture.h \
		headers/misc/oal_manager.h \
		headers/engine/loader.h \
		headers/engine/EngineManager.h \
		headers/engine_types.h \
		headers/ogl/ogl.h \
		headers/render/zs-uniform-buffer.h \
		headers/render/zs-shader.h \
		headers/engine.h \
		headers/vulkan/zsvulkan.h \
		headers/engine/engine_window.h \
		headers/world/zs-camera.h \
		headers/vulkan/vk_data.h \
		headers/render/zs-pipeline.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o zs-mesh.o src/render/zs-mesh.cpp

EngineManager.o: src/engine/EngineManager.cpp headers/engine/EngineManager.h \
		headers/engine_types.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o EngineManager.o src/engine/EngineManager.cpp

zs-texture.o: src/render/zs-texture.cpp headers/render/zs-texture.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o zs-texture.o src/render/zs-texture.cpp

LuaScript.o: src/Scripting/LuaScript.cpp headers/Scripting/LuaScript.h \
		headers/Scripting/zsensdk.h \
		headers/world/World.h \
		headers/engine/resources.h \
		headers/render/zs-texture.h \
		headers/render/zs-mesh.h \
		headers/render/zs-math.h \
		headers/misc/oal_manager.h \
		headers/engine/loader.h \
		headers/engine/EngineManager.h \
		headers/engine_types.h \
		headers/ogl/ogl.h \
		headers/render/zs-uniform-buffer.h \
		headers/render/zs-shader.h \
		headers/engine.h \
		headers/vulkan/zsvulkan.h \
		headers/engine/engine_window.h \
		headers/world/zs-camera.h \
		headers/vulkan/vk_data.h \
		headers/render/zs-pipeline.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o LuaScript.o src/Scripting/LuaScript.cpp

loader.o: src/engine/loader.cpp headers/engine/loader.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o loader.o src/engine/loader.cpp

oal_manager.o: src/misc/oal_manager.cpp headers/misc/oal_manager.h \
		headers/render/zs-math.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o oal_manager.o src/misc/oal_manager.cpp

zsensdk.o: src/Scripting/zsensdk.cpp headers/Scripting/zsensdk.h \
		headers/world/World.h \
		headers/engine/resources.h \
		headers/render/zs-texture.h \
		headers/render/zs-mesh.h \
		headers/render/zs-math.h \
		headers/misc/oal_manager.h \
		headers/engine/loader.h \
		headers/engine/EngineManager.h \
		headers/engine_types.h \
		headers/ogl/ogl.h \
		headers/render/zs-uniform-buffer.h \
		headers/render/zs-shader.h \
		headers/engine.h \
		headers/vulkan/zsvulkan.h \
		headers/engine/engine_window.h \
		headers/world/zs-camera.h \
		headers/vulkan/vk_data.h \
		headers/render/zs-pipeline.h \
		headers/Scripting/LuaScript.h \
		headers/world/go_properties.h \
		headers/world/tile_properties.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o zsensdk.o src/Scripting/zsensdk.cpp

randomg.o: src/misc/randomg.cpp headers/misc/randomg.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o randomg.o src/misc/randomg.cpp

zsensdk_input.o: src/Scripting/zsensdk_input.cpp headers/Scripting/LuaScript.h \
		headers/Scripting/zsensdk.h \
		headers/world/World.h \
		headers/engine/resources.h \
		headers/render/zs-texture.h \
		headers/render/zs-mesh.h \
		headers/render/zs-math.h \
		headers/misc/oal_manager.h \
		headers/engine/loader.h \
		headers/engine/EngineManager.h \
		headers/engine_types.h \
		headers/ogl/ogl.h \
		headers/render/zs-uniform-buffer.h \
		headers/render/zs-shader.h \
		headers/engine.h \
		headers/vulkan/zsvulkan.h \
		headers/engine/engine_window.h \
		headers/world/zs-camera.h \
		headers/vulkan/vk_data.h \
		headers/render/zs-pipeline.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o zsensdk_input.o src/Scripting/zsensdk_input.cpp

ogl_mesh.o: src/ogl/ogl_mesh.cpp headers/ogl/ogl.h \
		headers/render/zs-mesh.h \
		headers/render/zs-math.h \
		headers/render/zs-uniform-buffer.h \
		headers/render/zs-shader.h \
		headers/engine.h \
		headers/vulkan/zsvulkan.h \
		headers/engine/engine_window.h \
		headers/engine/EngineManager.h \
		headers/engine_types.h \
		headers/world/zs-camera.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ogl_mesh.o src/ogl/ogl_mesh.cpp

vk_mesh.o: src/vulkan/vk_mesh.cpp headers/vulkan/vk_data.h \
		headers/render/zs-mesh.h \
		headers/render/zs-math.h \
		headers/render/zs-uniform-buffer.h \
		headers/render/zs-shader.h \
		headers/engine.h \
		headers/vulkan/zsvulkan.h \
		headers/engine/engine_window.h \
		headers/engine/EngineManager.h \
		headers/engine_types.h \
		headers/world/zs-camera.h \
		headers/vulkan/zsvk_mem.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vk_mesh.o src/vulkan/vk_mesh.cpp

ogl_uniform_buf.o: src/ogl/ogl_uniform_buf.cpp headers/ogl/ogl.h \
		headers/render/zs-mesh.h \
		headers/render/zs-math.h \
		headers/render/zs-uniform-buffer.h \
		headers/render/zs-shader.h \
		headers/engine.h \
		headers/vulkan/zsvulkan.h \
		headers/engine/engine_window.h \
		headers/engine/EngineManager.h \
		headers/engine_types.h \
		headers/world/zs-camera.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ogl_uniform_buf.o src/ogl/ogl_uniform_buf.cpp

zs-uniform-buffer.o: src/render/zs-uniform-buffer.cpp headers/render/zs-uniform-buffer.h \
		headers/game.h \
		headers/world/World.h \
		headers/engine/resources.h \
		headers/render/zs-texture.h \
		headers/render/zs-mesh.h \
		headers/render/zs-math.h \
		headers/misc/oal_manager.h \
		headers/engine/loader.h \
		headers/engine/EngineManager.h \
		headers/engine_types.h \
		headers/ogl/ogl.h \
		headers/render/zs-shader.h \
		headers/engine.h \
		headers/vulkan/zsvulkan.h \
		headers/engine/engine_window.h \
		headers/world/zs-camera.h \
		headers/vulkan/vk_data.h \
		headers/render/zs-pipeline.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o zs-uniform-buffer.o src/render/zs-uniform-buffer.cpp

vk_uniform_buf.o: src/vulkan/vk_uniform_buf.cpp headers/vulkan/vk_data.h \
		headers/render/zs-mesh.h \
		headers/render/zs-math.h \
		headers/render/zs-uniform-buffer.h \
		headers/render/zs-shader.h \
		headers/engine.h \
		headers/vulkan/zsvulkan.h \
		headers/engine/engine_window.h \
		headers/engine/EngineManager.h \
		headers/engine_types.h \
		headers/world/zs-camera.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vk_uniform_buf.o src/vulkan/vk_uniform_buf.cpp

zsvk_mem.o: src/vulkan/zsvk_mem.cpp headers/vulkan/zsvk_mem.h \
		headers/vulkan/zsvulkan.h \
		headers/engine/engine_window.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o zsvk_mem.o src/vulkan/zsvk_mem.cpp

ogl_shader.o: src/ogl/ogl_shader.cpp headers/ogl/ogl.h \
		headers/render/zs-mesh.h \
		headers/render/zs-math.h \
		headers/render/zs-uniform-buffer.h \
		headers/render/zs-shader.h \
		headers/engine.h \
		headers/vulkan/zsvulkan.h \
		headers/engine/engine_window.h \
		headers/engine/EngineManager.h \
		headers/engine_types.h \
		headers/world/zs-camera.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o ogl_shader.o src/ogl/ogl_shader.cpp

vk_shader.o: src/vulkan/vk_shader.cpp headers/vulkan/vk_data.h \
		headers/render/zs-mesh.h \
		headers/render/zs-math.h \
		headers/render/zs-uniform-buffer.h \
		headers/render/zs-shader.h \
		headers/engine.h \
		headers/vulkan/zsvulkan.h \
		headers/engine/engine_window.h \
		headers/engine/EngineManager.h \
		headers/engine_types.h \
		headers/world/zs-camera.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o vk_shader.o src/vulkan/vk_shader.cpp

####### Install

install_target: first FORCE
	@test -d $(INSTALL_ROOT)/usr/lib || mkdir -p $(INSTALL_ROOT)/usr/lib
	-$(QINSTALL) $(TARGET) $(INSTALL_ROOT)/usr/lib/$(TARGET)

uninstall_target: FORCE
	-$(DEL_FILE) $(INSTALL_ROOT)/usr/lib/$(TARGET)
	-$(DEL_DIR) $(INSTALL_ROOT)/usr/lib/ 


install: install_target  FORCE

uninstall: uninstall_target  FORCE

FORCE:

